### ISSUE TITLE
Add an extra layer of testing using @babel/generator

### ISSUE THREAD

**Issue by Markos-Th09** [coderaiser/swc-to-babel#11]
Test cases can be faulty (this actually happened with the getters and setters PR) and the AST produced by this library may be invalid. The only real way to test if the AST is valid is to use @babel/generator to try to generate code from it.

**Comment by Markos-Th09** [comment]
I made this kind of testing with the help of eslint, counting fatal/unfixable errors in the code generated by @babel/generator. I assume if there are fatal errors the ast generated was invalid

**Comment by coderaiser** [comment]
That’s and interesting idea!

**Comment by Markos-Th09** [comment]
> 

One problem is that typescript doesn't quite work with this

**Comment by Markos-Th09** [comment]
I think I have a working implementation of this. Should I make a PR?

**Comment by coderaiser** [comment]
Yes, it would be great

**Comment by coderaiser** [comment]
I simplified things a bit:
- added a new operator `compile`;
- used `print` from `putout` and just check if it can be generated or not;
- I think we can check things without ESLint for now;

Thanks a lot for ideas! With your help tests looks much simpler :)

**Comment by Markos-Th09** [comment]
> I simplified things a bit:
> 
> * added a new operator `compile`;
> * used `print` from `putout` and just check if it can be generated or not;
> * I think we can check things without ESLint for now;
> 
> Thanks a lot for ideas! With your help tests looks much simpler :)
I just don't know your testing framework and this `putout` tool so I just solved it with the tools I know. They seem like really interesting tools that I could definitely use in future projects.

**Comment by coderaiser** [comment]
How do you use `swc-to-babel` by the way :)?

**Comment by Markos-Th09** [comment]
> 

Well it started with the idea I wanted to make compilation times fast in react native. Metro transformers need to return a babel ast so I needed some kind of conversion and I found `swc-to-babel`. While trying to make this work I discovered all of those bugs.

**Comment by Markos-Th09** [comment]
The `print` function from putout never seems to throw an exception even if an ast is invalid in a node known to babel.  Since all the files are formatted according to putout rules doing an equals assertion would make this actually work completely as it should

**Comment by coderaiser** [comment]
What if `generate` will be used from `putout`?

**Comment by Markos-Th09** [comment]
> What if `generate` will be used from `putout`?

generate was the same behaviour

**Comment by coderaiser** [comment]
What AST are you trying?

**Comment by coderaiser** [comment]
What if we use `parse(print(ast))` and check that printed is the same ast :)?

**Comment by Markos-Th09** [comment]
> What if we use `parse(print(ast)) === ast` and check that parsed is the same ast :)?

It is still not a solution because the ast in the test may not match the source in the first place. I don't there is a great solution on this
