### ISSUE TITLE
Holey ArrayExpressions error

### ISSUE THREAD

**Issue by j4k0xb** [coderaiser/swc-to-babel#17]
> TypeError: Cannot destructure property 'spread' of 'arg' as it is null.
> at maybeConvertSpread (node_modules/swc-to-babel/lib/swc/index.js:195:12)
>  at Array.forEach (<anonymous>)
>  at module.exports.ArrayExpression (node_modules/swc-to-babel/lib/swc/index.js:216:24)

js input:
```js
[,];
```
swc ast for the array:

```json
{
  "type": "ArrayExpression",
  "span": {
    "start": 1,
    "end": 4,
    "ctxt": 0
  },
  "elements": [
    null
  ]
}
```

**Comment by coderaiser** [comment]
Are you up for a PR?

**Comment by j4k0xb** [comment]
sure, I'll create one soon
