### ISSUE TITLE
`span` doesn't convert to `loc`

### ISSUE THREAD

**Issue by ifshizuku** [coderaiser/swc-to-babel#19]
the code:

<img width="369" alt="image" src="https://github.com/coderaiser/swc-to-babel/assets/73536163/b2e17002-e7b4-434d-ab36-bffe456c5a12">

the output doesn't have the `loc` key while `span` are existed:

<img width="586" alt="image" src="https://github.com/coderaiser/swc-to-babel/assets/73536163/80babe67-10e9-4d9c-8ad7-84d051b157e9">

**Comment by coderaiser** [comment]
Are you up for a PR?

**Comment by ifshizuku** [comment]
i'll try to fix it tomorrow, it seems to have much more problems about this.

**Comment by ifshizuku** [comment]
what package manager you used? npm, yarn or pnpm? the git repo doesn't contain any of those lock file.

**Comment by ifshizuku** [comment]
your test system has some incredible error, the input test js file will be parse like a stream. The AST the test `compile` made will continue the every test sent into it, from `'swc-module'` to `'parenthesized-const-assertion'`, the offset will accrual one by one and make a large offset number on file.

like the first one:

<img width="541" alt="image" src="https://github.com/coderaiser/swc-to-babel/assets/73536163/1accbede-9e68-4243-8bdf-3d3fc621c75b">

and the end one:
<img width="529" alt="image" src="https://github.com/coderaiser/swc-to-babel/assets/73536163/a09031da-6067-4211-aa59-1ceb20e03c1b">

pay attention to the span data, the offset is increasing.

@coderaiser 

I've make the change to fix the `loc`'s not be added to the JSX Element and fix the wrong line number the original code gave.

**Comment by ifshizuku** [comment]
This bug may be this: https://github.com/swc-project/swc/issues/1366 (two y.o. not fixing)
