### ISSUE TITLE
The example in the README doesn't work without a second parameter

### ISSUE THREAD

**Issue by Markos-Th09** [coderaiser/swc-to-babel#4]
Something which isn't mentioned in the docs is that the function needs to take a second argument. This argument is optionally the source code or an empty string if it isn't available. As it isn't necessarily required but it is good to pass I think it should be optional. Also I think there should be an api reference in the README.

**Comment by coderaiser** [comment]
Good point! It’s necessary if you need positions instead of spans.

**Comment by Markos-Th09** [comment]
> Good point! It’s necessary if you need positions instead of spans.

Should I go ahead to make a PR making it optional?

**Comment by coderaiser** [comment]
I think locations is very important information, and better to mention that source must be passed.

**Comment by Markos-Th09** [comment]
> I think locations is very important information, and better to mention that source must be passed.

From my test all babel tools can work without it, things like babel/traverse, babel/generator, babel/types, etc

**Comment by coderaiser** [comment]
OK, if you see the cases when locations not needed, we can add it such an option :). Are you up for a PR?

**Comment by Markos-Th09** [comment]
> <img alt="@coderaiser" width="40" height="40" src="https://avatars.githubusercontent.com/u/1573141?s=88&amp;v=4">

well the fix is just like 3 charachters so I can make this pr in 5 seconds lol

**Comment by coderaiser** [comment]
Landed in [v1.25.0](https://github.com/coderaiser/swc-to-babel/releases/tag/v1.25.0) 🎉
