### ISSUE TITLE
Why is the espree parser used in example.js instead of the swc parser

### ISSUE THREAD

**Issue by Markos-Th09** [coderaiser/swc-to-babel#5]
In the README `@swc/core` is used which seems like the right thing. But why the espree parser in `example.js`?

**Comment by coderaiser** [comment]
Could you please update?

**Comment by Markos-Th09** [comment]
> Could you please update?
In README the example code is
```js
const swc = require('@swc/core');
const toBabel = require('swc-to-babel');
const traverse = require('@babel/traverse').default;

const ast = toBabel(swc.parseSync(`
    const f = ({a}) => a;
`));

traverse({
    ObjectProperty(path) {
        console.log(path.value.name);
        // output
        'a';
    },
});
```
In here `@swc/core` is used the parse the code which demonstrates this library correctly

In example.js the code is
```js
'use strict';

const cherow = require('espree');
const toBabel = require('.');
const traverse = require('@babel/traverse').default;

const ast = toBabel(cherow.parse(`
    const f = ({a}) => a;
`));

traverse(ast, {
    noScope: false,
    ObjectProperty(path) {
        console.log(`variable is "${path.node.value.name}"`);
        // output
        'a';
    },
});
```
In example.js `@swc/core` isn't used to parse the code which doesn't make sense

**Comment by coderaiser** [comment]
> In example.js @swc/core isn't used to parse the code which doesn't make sense

Absolutely agree, we can remove it or update, are you up for a PR :)?

**Comment by Markos-Th09** [comment]
> > In example.js @swc/core isn't used to parse the code which doesn't make sense
> 
> Absolutely agree, we can remove it or update, are you up for a PR :)?

Yes I do have pr ready but before publishing I thought I had to ask about this

**Comment by Markos-Th09** [comment]
Also is this related from this being based on your `estree-to-babel` package?

**Comment by coderaiser** [comment]
> Also is this related from this being based on your estree-to-babel package?

yes
